feat: add support for variables in subgraphRequest function
snapshot-labs/snapshot.js pull request #1047
Opened 2024-08-20 15:29 UTC by wa0x6e

This PR adds support for variable when sending graphql request via the `subgraphRequest` utils function.

Injecting `variables` via the `options` argument is very ugly, but in order to be backward compatible, this seems to be the only way.

### How to test

```ts
import { VariableType } from 'json-to-graphql-query';

const result = await subgraphRequest(
    'https://hub.snapshot.org/graphql',
    {
      __variables: {
        id: 'String!'
      },
      space: {
        __args: {
          id: new VariableType('id')
        },
        id: true,
        name: true
      }
    },
    {
      variables: {
        id: 'aave.eth'
      }
    }
  );
  console.log(result);
```

It should print 

```ts
{ space: { id: 'aave.eth', name: 'Aave' } }
```

2024-08-20 16:51 UTC, ChaituVR commented
Where do we want to use this?

2024-08-20 17:48 UTC, wa0x6e commented
In sequencer, in the delegate statement pr. Some graphql api does not work with the hardcoded variables inside the query, since they don't use string type, but enum

2024-08-20 18:19 UTC, ChaituVR requested changes

2024-08-20 18:19 UTC, ChaituVR commented on src/utils.ts
> +  if (body) body.variables = options.variables;
I think body will always exist
```suggestion
  if (options.variables) body.variables = options.variables;
```

2024-08-21 08:14 UTC, ChaituVR approved these changes
tAck

2024-08-21 08:16 UTC, merged