Add Strategies - Modefi
snapshot-labs/snapshot.js pull request #288
Opened 2021-07-05 04:36 UTC by Modefi

Fixes # .

Changes proposed in this pull request:
- Add Strategies
- 
-

2021-07-05 05:44 UTC, ChaituVR requested changes

2021-07-05 05:44 UTC, ChaituVR commented on src/strategies/modefiMultichain/index.ts
> +  '250': 'https://api.thegraph.com/subgraphs/name/ord786/fantom-blocks'
Looks like this is just a copy of `multichain` strategy, is there any reason to make it seperate? I think you can use `multichain` strategy in your space and that strategy can support this networt

https://github.com/snapshot-labs/snapshot.js/blob/master/src/strategies/multichain/examples.json#L41-L43

2021-07-05 05:44 UTC, ChaituVR commented on src/strategies/index.ts
> +  'modefiStaking': modefiStaking,
The strategy name should be like this.. can u plz rename the folder name too.. 

```suggestion
  'modefi-staking': modefiStaking,
```

2021-07-05 19:57 UTC, Modefi commented
Strategy updated

2021-07-06 05:16 UTC, ChaituVR reviewed
LGTM

2021-07-08 15:57 UTC, bonustrack approved these changes

2021-07-08 15:57 UTC, merged