Badgeth strategy
snapshot-labs/snapshot.js pull request #299
Opened 2021-07-08 17:42 UTC by HardForksOverKnives

Adds Badgeth strategy

2021-07-09 03:45 UTC, ChaituVR commented on src/strategies/index.ts
> +  'badgeth': badgeth
```suggestion
  'badgeth': badgeth,
```

2021-07-11 16:57 UTC, ChaituVR reviewed
LGTM

2021-07-11 16:59 UTC, bonustrack requested changes
The strategy should return only checksumed addresses (not lowercased addrrsses), you can checksum address with This function `import { getAddress } from '@ethersproject/address';`.

2021-07-12 04:39 UTC, HardForksOverKnives commented
Checksummed addresses

2021-07-13 09:16 UTC, bonustrack commented on src/strategies/badgeth/index.ts
> +  console.log("result: ", result);
You shouldn't add console.log in the strategy
```suggestion
```

2021-07-13 09:16 UTC, bonustrack commented on src/strategies/badgeth/index.ts
> +  console.log("sending subgraph request");
```suggestion
```

2021-07-13 09:17 UTC, bonustrack approved these changes

2021-07-13 09:18 UTC, merged