Naga Power Stategy
snapshot-labs/snapshot.js pull request #307
Opened 2021-07-14 05:55 UTC by NuttakitDW

Fixes # .

Changes proposed in this pull request:
- naga-power strategy

2021-07-14 09:44 UTC, ChaituVR requested changes

2021-07-14 09:44 UTC, ChaituVR commented on package.json
> +    "@snapshot-labs/snapshot.js": "^0.1.11",
we are inside @snapshot-labs/snapshot.js... we don't need this.. you can remove it
```suggestion
```

2021-07-14 09:44 UTC, ChaituVR commented on package.json
> +    "@snapshot-labs/snapshot.js": "^0.1.11",
also, revert package-lock.json

2021-07-14 09:47 UTC, ChaituVR requested changes
Looks like this is just a copy of `erc20-balance-of ` strategy. . you can use the same strategy in your space, with your own params

2021-08-16 13:11 UTC, bonustrack commented
Closing this PR for now, new strategies must be added into this repository now: https://github.com/snapshot-labs/snapshot-strategies, feel free to reopen this PR if needed.

2021-08-16 13:11 UTC, closed without merging