[zrx-voting-power] ZRX voting power strategy
snapshot-labs/snapshot.js pull request #309
Opened 2021-07-15 00:35 UTC by lyaunzbe

Hello! I work with 0x labs on the platform side. I am making this PR to hopefully add the zrx-voting-power strategy (calculates voting power based on staked + wallet balances). Thank you!

Fixes # .

Changes proposed in this pull request:
- 
- 
-

2021-07-15 01:19 UTC, OhArthits approved these changes

2021-07-15 10:16 UTC, ChaituVR requested changes

2021-07-15 10:16 UTC, ChaituVR commented on src/strategies/zrx-voting-power/index.ts
> +];
```suggestion
const abi = [
  'function getVotingPower(address account, bytes32[] operatedPoolIds) view returns (uint256 votingPower)'
]
```

2021-07-15 21:41 UTC, lyaunzbe commented on src/strategies/zrx-voting-power/index.ts
> +];
thank you, i've made this change

2021-07-16 17:00 UTC, ChaituVR commented
@lyaunzbe there is conflict, can u resolve it plz :) everything else looks good to me

2021-07-17 03:06 UTC, lyaunzbe commented
@ChaituVR should be all set now, thank you!

2021-07-18 21:10 UTC, bonustrack commented on src/strategies/zrx-voting-power/index.ts
> +      : await provider.getBlockNumber(snapshot);
You don't need to query for current block number here, 'latest' will work.
```suggestion
      : 'latest';
```

2021-07-18 21:11 UTC, bonustrack approved these changes
Looks good!

2021-07-18 21:11 UTC, merged