Add unipool-same-token strategy
snapshot-labs/snapshot.js pull request #310
Opened 2021-07-15 08:28 UTC by dapplion

Generic strategy for UniPool contract where the staked token equals the earned token

2021-07-15 10:08 UTC, ChaituVR requested changes

2021-07-15 10:08 UTC, ChaituVR commented on src/strategies/index.ts
> +  'impossible-finance': impossibleFinance,
plz remove this line

2021-07-15 10:11 UTC, dapplion commented on src/strategies/index.ts
> +  'impossible-finance': impossibleFinance,
Done

2021-07-15 10:23 UTC, ChaituVR requested changes

2021-07-15 10:23 UTC, ChaituVR commented on src/strategies/unipool-same-token/index.ts
> +];
```suggestion
const contractAbi = [
  'function balanceOf(address account) view returns (uint256)',
  'function earned(address account) view returns (uint256)'
];
```

2021-07-15 10:23 UTC, ChaituVR commented on src/strategies/unipool-same-token/examples.json
> +      "0xc5df4d5ed23f645687a867d8f83a41836fcf8811"
```✕ File examples.json should include at least 1 address with a positive score (3 ms)```
 
Please add a token address here, which can return a positive score

2021-07-15 10:23 UTC, ChaituVR commented on src/strategies/unipool-same-token/examples.json
> +    "snapshot": "11635000"
```✕ File examples.json must use a snapshot block number in the past (3 ms) ```
should be a number
```suggestion
    "snapshot": 11635000
```

2021-07-15 14:39 UTC, ChaituVR reviewed
LGTM

2021-07-16 11:59 UTC, dapplion commented
Kind bump

2021-07-16 14:04 UTC, dapplion commented
Kind bump

2021-07-16 14:20 UTC, bonustrack approved these changes

2021-07-16 14:20 UTC, merged