added new strategy
snapshot-labs/snapshot.js pull request #345
Opened 2021-07-29 07:02 UTC by ash-greninja-poke

Fixes # .

Changes proposed in this pull request:
- 
- 
-

2021-07-29 08:17 UTC, ash-greninja-poke commented
@bonustrack @ChaituVR please review the new strategy.

2021-07-29 18:40 UTC, ash-greninja-poke commented
@ChaituVR @bonustrack will you please start the reviewing process

2021-07-30 11:37 UTC, ash-greninja-poke commented
@ChaituVR @bonustrack guys please merge it seems like test cases has passes successfully.

2021-07-30 17:09 UTC, ChaituVR requested changes

2021-07-30 17:09 UTC, ChaituVR commented on src/strategies/planet-finance/index.ts
> +  ]
```suggestion
export const bep20Abi: any = [
  'function totalSupply() view returns (uint256)',
  'function balanceOf(address) view returns (uint256)'
]
```

2021-07-30 17:09 UTC, ChaituVR commented on src/strategies/planet-finance/index.ts
> +]
Please change this to 
```
[  
  'function balanceOf() view returns (uint256)',
  'function totalShares() view returns (uint256)',
  'function userInfo(address) view returns (uint256 shares, uint256 lastDepositedTime, uint256 cakeAtLastUserAction, uint256 lastUserActionTime)' 
]
  ```

2021-07-31 09:17 UTC, ash-greninja-poke commented
@ChaituVR request changes are now done

2021-08-01 11:13 UTC, ChaituVR commented
LGTM

2021-08-02 08:58 UTC, merged