Poap with weight , added supply parameter
snapshot-labs/snapshot.js pull request #347
Opened 2021-07-30 13:38 UTC by Rashmi-278

Fixes # .

Changes proposed in this pull request:
-  gql query created
-  used utils to query

2021-07-30 17:12 UTC, ChaituVR requested changes
Hello, Please revert changes in the `package-lock.json` file, which is failing the build/checks, Thanks

2021-07-30 17:16 UTC, ChaituVR requested changes

2021-07-30 17:16 UTC, ChaituVR commented on src/strategies/poap-with-weight/index.ts
> +// `;
```suggestion
```

2021-07-30 17:16 UTC, ChaituVR commented on src/strategies/poap-with-weight/index.ts
> +  // return response[0].owner;
```suggestion
```

2021-07-30 17:16 UTC, ChaituVR commented on src/strategies/poap-with-weight/index.ts
> +export const author = 'G2 & Torch';
This should be a GitHub Id

2021-08-02 13:57 UTC, bonustrack commented
@Rashmi-278 Hi! We've moved the strategies to another repository here:  https://github.com/snapshot-labs/snapshot-strategies Could you make your PR there? Sorry for the trouble!

2021-08-16 13:10 UTC, bonustrack commented
Closing this PR for now, new strategies must be added into this repository now: https://github.com/snapshot-labs/snapshot-strategies, feel free to reopen this PR if needed.

2021-08-16 13:10 UTC, closed without merging