Added Nahmii Testnet
snapshot-labs/snapshot.js pull request #446
Opened 2021-12-09 18:28 UTC by jonddon

Added Nahmii Testnet

2021-12-09 18:37 UTC, ChaituVR requested changes

2021-12-09 18:37 UTC, ChaituVR commented on src/networks.json
> +    "5553": {
```suggestion
  },
  "5553": {
```

2021-12-09 18:38 UTC, ChaituVR commented
Works good @bonustrack 

![image](https://user-images.githubusercontent.com/15967809/145455867-f63aedf7-3c2f-4b84-a5b7-6da7fbe71efe.png)

2021-12-11 12:29 UTC, bonustrack commented
@jonddon The image should be a square, can you change it?

2021-12-11 15:25 UTC, jonddon commented
> 

I have changed the logo

2021-12-11 15:25 UTC, closed without merging

2021-12-11 15:29 UTC, jonddon commented
> @jonddon The image should be a square, can you change it?

I have updated the logo