Add SX Network Mainnet
snapshot-labs/snapshot.js pull request #585
Opened 2022-05-24 15:54 UTC by dankostiuk

Fixes # .

Changes proposed in this pull request:
- add SX Network mainnet

2022-05-25 07:31 UTC, ChaituVR requested changes

2022-05-25 07:31 UTC, ChaituVR commented on src/networks.json
> +    "logo": "ipfs://QmSXLXqyr2H6Ja5XrmznXbWTEvF2gFaL8RXNXgyLmDHjAF"
@dankostiuk Did you pin this image somewhere? not able to resolve this , i would suggest to use a service like pinnata or fleek to pin this image to IPFS

2022-05-25 07:31 UTC, ChaituVR commented on src/networks.json
> +    "logo": "ipfs://QmSXLXqyr2H6Ja5XrmznXbWTEvF2gFaL8RXNXgyLmDHjAF"
Everything else looks good

2022-06-27 13:59 UTC, mrwillis commented
@ChaituVR are there any other changes you'd need to get this merged?

2022-06-27 17:45 UTC, ChaituVR commented
Hey @dankostiuk looks good, can you update the branch plz

2022-06-28 20:00 UTC, bonustrack approved these changes

2022-07-04 17:12 UTC, ChaituVR commented
Sorry for not noticing this @dankostiuk Can you plz update the branch again, or click on Allow update from maintainers so i can update when we merge this😅

2022-07-04 17:20 UTC, ChaituVR approved these changes

2022-07-04 17:20 UTC, merged