Update networks.json
snapshot-labs/snapshot.js pull request #663
Opened 2022-07-18 02:20 UTC by xuzuguang

Add AITD Mainnet config to config file

- 
- 
-

2022-07-20 07:13 UTC, ChaituVR requested changes

2022-07-20 07:13 UTC, ChaituVR commented on src/networks.json
> +      "http://node.aitd.io"
Hi @xuzuguang This RPC doesn't work, i get CORS issues,http://walletrpc.aitd.io but it is not a full archive node

2022-07-21 21:00 UTC, ChaituVR requested changes
Everything else looks good 🚀

2022-07-21 21:00 UTC, ChaituVR commented on src/networks.json
> +    "logo": "ipfs://QmXbBMMhjTTGAGjmqMpJm3ufFrtdkfEXCFyXYgz7nnZzsy"
Looks like this IPFS is not pinned @xuzuguang Use a third-party provider like pinnata to pin this :) 

https://ipfs.io/ipfs/QmXbBMMhjTTGAGjmqMpJm3ufFrtdkfEXCFyXYgz7nnZzsy

2022-07-25 19:48 UTC, bonustrack approved these changes

2022-07-26 04:52 UTC, ChaituVR approved these changes

2022-07-26 04:58 UTC, merged