Add Flare related networks
snapshot-labs/snapshot.js pull request #716
Opened 2022-09-07 12:49 UTC by RareData

Changes proposed in this pull request:
- Add Flare Mainnet (https://chainlist.org/chain/14)
- Add Flare Testnet Coston (https://chainlist.org/chain/16)
- Add Songbird Canary-Network (https://chainlist.org/chain/19)

2022-09-10 15:10 UTC, HariSeldon23 commented
Hey @ChaituVR would you be able to review when you get a chance?

2022-09-12 07:47 UTC, ChaituVR requested changes

2022-09-12 07:47 UTC, ChaituVR commented on src/networks.json
> +      "https://sgb-rpc.ftso.eu"
Only the first RPC is a full archive node.
```suggestion
      "https://songbird-api.flare.network/ext/C/rpc"
```

2022-09-12 07:47 UTC, ChaituVR commented on src/networks.json
> +    "start": 22501833,
Multicall creation block
```suggestion
    "start": 21807126,
```

2022-09-12 07:47 UTC, ChaituVR commented on src/networks.json
> +    "start": 5042953,
```suggestion
    "start": 4782058,
```

2022-09-12 07:47 UTC, ChaituVR commented on src/networks.json
> +    "multicall": "0x0c7B6FC9ffaBC273E9934383f258294A00Db7Fc3",
Hello @RareData Verify and publish contract code [here ](https://flare-explorer.flare.network/address/0x0c7B6FC9ffaBC273E9934383f258294A00Db7Fc3/contracts) plz :)

2022-09-12 07:47 UTC, ChaituVR commented on src/networks.json
> +    "start": 946850,
```suggestion
    "start": 936246,
```

2022-09-12 07:47 UTC, ChaituVR commented
Everything else looks good :)

2022-10-10 15:52 UTC, RareData commented
We'll be updating the logos and some of the multicall deployments, please hold off for now.

2022-10-12 11:11 UTC, RareData commented
> Everything else looks good :)

Ready for another review. All comments should be fixed.

2022-10-12 11:44 UTC, ChaituVR commented
Awesome! I will take a look, Can update the base branch plz?

2022-10-12 11:55 UTC, RareData commented
Done

2022-10-12 12:20 UTC, merged