Pass headers to score API
snapshot-labs/snapshot.js pull request #757
Opened 2022-11-11 19:58 UTC by ChaituVR

Related to https://github.com/snapshot-labs/score-api/pull/483

2022-12-06 00:04 UTC, Heheehd approved these changes

2023-11-06 08:15 UTC, wa0x6e commented
Can you resolve conflicts ? This is an useful update

2023-11-06 08:19 UTC, wa0x6e requested changes

2024-04-11 07:52 UTC, IndigoFlo approved these changes

2024-08-05 14:11 UTC, closed without merging