feat: replace client endpoint to sequencer
snapshot-labs/snapshot.js pull request #764
Opened 2022-12-04 13:24 UTC by bonustrack

2022-12-13 17:57 UTC, ChaituVR requested changes

2022-12-13 17:57 UTC, ChaituVR commented on src/constants.json
> +    "hub": "https://hub.snapshot.org",
I get `snapshot.min.js:15          POST https://hub.snapshot.org/ 404` error when i try to vote @bonustrack

2022-12-13 17:58 UTC, ChaituVR commented on src/constants.json
> +    "hub": "https://hub.snapshot.org",
I use same code as here https://docs.snapshot.org/snapshot.js#init-client

2023-01-29 12:07 UTC, bonustrack commented
Can you debug this PR @ChaituVR ?

2023-01-29 13:35 UTC, ChaituVR reviewed
There was a issue with `.replace` so it was not working. fixed it now 👍

2023-01-29 13:36 UTC, ChaituVR approved these changes

2023-01-29 13:36 UTC, merged