Add Evmos Network
snapshot-labs/snapshot.js pull request #768
Opened 2022-12-19 16:09 UTC by NoahMarconi

Changes proposed in this pull request:

Add canto network ([https://chainlist.org/chain/9001](https://chainlist.org/chain/9001))

2022-12-21 07:19 UTC, ChaituVR requested changes
@NoahMarconi Looks like none of these RPC nodes are full archive nodes, we need to full archive node to be able to support

2022-12-21 07:24 UTC, ChaituVR commented
Also need to verify and publish code here https://escan.live/address/0x2764b262e60d3ac96999f7e73b0628b09cbb367e#contract

2022-12-23 14:46 UTC, NoahMarconi commented
I've now updated with an archival rpc provided by the evmos team and linked to thier blockscout explorer.

2022-12-23 18:02 UTC, NoahMarconi commented
@ChaituVR evmos informed me no public archival nodes will exist prior to the restart. POST restart, the above should do it.

What blockheight do you need?

2022-12-29 12:00 UTC, ChaituVR commented on src/networks.json
> +    "multicall": "0x2764b262E60D3Ac96999F7e73b0628B09CbB367E",
https://blockscout.evmos.org/address/0x2764b262E60D3Ac96999F7e73b0628B09CbB367E/contracts#address-tabs Can verify and publish code here?

2022-12-29 12:02 UTC, ChaituVR commented on src/networks.json
> +    "multicall": "0x2764b262E60D3Ac96999F7e73b0628B09CbB367E",
>  evmos informed me no public archival nodes will exist prior to the restart. POST restart, the above should do it.
What blockheight do you need?

@NoahMarconi It should atleast work from multicall contract creation block, i.e 59316 in this case

2022-12-29 12:03 UTC, ChaituVR commented on src/networks.json
> +    "start": 8791997,
```suggestion
    "start": 59316,
```

2023-05-22 01:36 UTC, ChaituVR commented
Closing this as stale, feel free to reopen if needed

2023-05-22 01:36 UTC, closed without merging