Update Chain ID Shimmer EVM Testnet in networks.json
snapshot-labs/snapshot.js pull request #874
Opened 2023-07-21 23:51 UTC by Phyloiota

The Testnet was reset and moved to Chain ID 1072. ID 1071 does not exist any longer. Submitted new Chain ID and Multical contract

Fixes # .

Changes proposed in this pull request:
-  new Chain ID
- new Multicall contract
-

2023-07-23 19:20 UTC, ChaituVR requested changes
Hi @Phyloiota 

looks like this RPC node is not a full archive node? can check?
I get this error
```
fullArchiveNode Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":44,\"error\":{\"code\":-32000,\"message\":\"root commitment '2d168960809f4582d3b6a9ce04798e2e18b7146f' does not exist\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_getBalance\",\"params\":[\"0x751d21047c116413895c259f3f305e38c10b7cf6\",\"0x1\"],\"id\":44,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://json-rpc.evm.testnet.shimmer.network/", code=SERVER_ERROR, version=web/5.6.0)
````

2023-07-23 19:20 UTC, ChaituVR commented on src/networks.json
>      "start": 7282345,
```suggestion
    "start": 10614,
```

2023-08-05 02:30 UTC, Phyloiota reviewed
Hey, sorry was not following up here. This is the correct archive node now

2023-08-05 02:30 UTC, Phyloiota commented on src/networks.json
>        "https://json-rpc.evm.testnet.shimmer.network/"
```suggestion
      "https://archive.evm.testnet.shimmer.network/v1/chains/rms1pr75wa5xuepg2hew44vnr28wz5h6n6x99zptk2g68sp2wuu2karywgrztx3/evm"
```

2023-08-06 20:08 UTC, ChaituVR approved these changes

2023-08-06 20:08 UTC, ChaituVR commented
Hi @Phyloiota This will be updated in the next update. (may take some time)

2023-08-06 20:09 UTC, merged