Add: Neon Devnet and Neon Mainnet
snapshot-labs/snapshot.js pull request #876
Opened 2023-07-30 17:34 UTC by joehquak

This PR adds the Neon Devnet and Mainnet to Snapshot

Neon EVM was launched to public on 17th July 2023 during ETHCC

References:
Mainnet: https://chainlist.org/chain/245022934
Devnet: https://chainlist.org/chain/245022926

2023-07-30 17:37 UTC, joehquak commented
Just want to also double check that `start:` refers to the starting block to index from? If so then my implementation should be correct.

2023-07-30 18:48 UTC, ChaituVR requested changes
Hi @joehquak We have changed our process to add new networks, refer https://docs.snapshot.org/developer-guides/networks

2023-07-30 19:04 UTC, joehquak commented
Hey @ChaituVR 
Just submitted 2 requests, one for each network

Just an FYI, the IPFS field doesn't accept `ipfs://` addresses, I had to use a `https://` address via cloudflare

Thanks

2023-07-31 07:26 UTC, ChaituVR commented
Hey @joehquak To support these networks the network request should be coming from the Neon EVM team itself

2023-07-31 19:22 UTC, joehquak commented
> Hey @joehquak To support these networks the network request should be coming from the Neon EVM team itself

Hi @ChaituVR I'm a partner of Neon however if you like I can get one of the team members to comment on this PR?

2023-08-01 09:50 UTC, ChaituVR commented
Better to respond directly on the form in docs, they can add dummy data on network fields, I will merge these both requests into one

2026-05-17 01:41 UTC, closed without merging